// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {gui} from '../models';

export function GenerateLeads(arg1:string,arg2:string,arg3:Array<number>,arg4:string,arg5:string):Promise<void>;

export function GetAdvertisements():Promise<Array<dtos.Ad>>;

export function GetCinemas(arg1:string,arg2:number):Promise<Array<dtos.Cinema>>;

export function GetDefaultOutputDirectory():Promise<string>;

export function GetSchedulingStrategies():Promise<Array<gui.adSchedulingStrategyDescriptor>>;

export function GetScreenTypes():Promise<Array<dtos.ScreenType>>;

export function GetStoredSchedules():Promise<Array<string>>;

export function SelectOutputDirectory():Promise<string>;
