// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateLeads(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['gui']['App']['GenerateLeads'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAdvertisements() {
  return window['go']['gui']['App']['GetAdvertisements']();
}

export function GetCinemas(arg1, arg2) {
  return window['go']['gui']['App']['GetCinemas'](arg1, arg2);
}

export function GetDefaultOutputDirectory() {
  return window['go']['gui']['App']['GetDefaultOutputDirectory']();
}

export function GetSchedulingStrategies() {
  return window['go']['gui']['App']['GetSchedulingStrategies']();
}

export function GetScreenTypes() {
  return window['go']['gui']['App']['GetScreenTypes']();
}

export function GetStoredSchedules() {
  return window['go']['gui']['App']['GetStoredSchedules']();
}

export function SelectOutputDirectory() {
  return window['go']['gui']['App']['SelectOutputDirectory']();
}
